package com.briup.Hospital.bean.extend;

import com.briup.Hospital.bean.Drug;
import com.briup.Hospital.bean.Patient;

public class PatientDrugVM {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.cost
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.patient_id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Patient patient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.drug_id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Drug drug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.num
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientdrug.id
     *
     * @return the value of patientdrug.id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientdrug.id
     *
     * @param id the value for patientdrug.id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientdrug.cost
     *
     * @return the value of patientdrug.cost
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientdrug.cost
     *
     * @param cost the value for patientdrug.cost
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

   

    public Patient getPatient() {
		return patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public Drug getDrug() {
		return drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientdrug.num
     *
     * @return the value of patientdrug.num
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientdrug.num
     *
     * @param num the value for patientdrug.num
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}