package com.briup.Hospital.bean.extend;

import com.briup.Hospital.bean.Patient;
import com.briup.Hospital.bean.Physicalexam;

public class PatientPhysicalexamVM {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientphysicalexam.id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientphysicalexam.cost
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientphysicalexam.patient_id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Patient patient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientphysicalexam.physical_id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Physicalexam physicalexam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientphysicalexam.id
     *
     * @return the value of patientphysicalexam.id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientphysicalexam.id
     *
     * @param id the value for patientphysicalexam.id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientphysicalexam.cost
     *
     * @return the value of patientphysicalexam.cost
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientphysicalexam.cost
     *
     * @param cost the value for patientphysicalexam.cost
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

	public Patient getPatient() {
		return patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public Physicalexam getPhysicalexam() {
		return physicalexam;
	}

	public void setPhysicalexam(Physicalexam physicalexam) {
		this.physicalexam = physicalexam;
	}

   
}