package com.briup.Hospital.bean.extend;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.briup.Hospital.Web.converter.DateJsonSerializer;
import com.briup.Hospital.bean.Patient;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

public class UserPatientVM {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.price
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.status
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.symptom
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private String symptom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.advice
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private String advice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.user_id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private UserVm user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.patient_id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private Patient patient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.date
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.complained
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private String complained;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.pastMedicalHistory
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private String pastmedicalhistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.historyOfPresentIllness
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private String historyofpresentillness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userpatient.physicalExamResult
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    private String physicalexamresult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.id
     *
     * @return the value of userpatient.id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.id
     *
     * @param id the value for userpatient.id
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.price
     *
     * @return the value of userpatient.price
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.price
     *
     * @param price the value for userpatient.price
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.status
     *
     * @return the value of userpatient.status
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.status
     *
     * @param status the value for userpatient.status
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.symptom
     *
     * @return the value of userpatient.symptom
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public String getSymptom() {
        return symptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.symptom
     *
     * @param symptom the value for userpatient.symptom
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setSymptom(String symptom) {
        this.symptom = symptom == null ? null : symptom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.advice
     *
     * @return the value of userpatient.advice
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public String getAdvice() {
        return advice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.advice
     *
     * @param advice the value for userpatient.advice
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setAdvice(String advice) {
        this.advice = advice == null ? null : advice.trim();
    }


    

   

	public UserVm getUser() {
		return user;
	}

	public void setUser(UserVm user) {
		this.user = user;
	}

	public Patient getPatient() {
		return patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.date
     *
     * @return the value of userpatient.date
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
	@JsonSerialize(using=DateJsonSerializer.class)
	public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.date
     *
     * @param date the value for userpatient.date
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.complained
     *
     * @return the value of userpatient.complained
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public String getComplained() {
        return complained;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.complained
     *
     * @param complained the value for userpatient.complained
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setComplained(String complained) {
        this.complained = complained == null ? null : complained.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.pastMedicalHistory
     *
     * @return the value of userpatient.pastMedicalHistory
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public String getPastmedicalhistory() {
        return pastmedicalhistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.pastMedicalHistory
     *
     * @param pastmedicalhistory the value for userpatient.pastMedicalHistory
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setPastmedicalhistory(String pastmedicalhistory) {
        this.pastmedicalhistory = pastmedicalhistory == null ? null : pastmedicalhistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.historyOfPresentIllness
     *
     * @return the value of userpatient.historyOfPresentIllness
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public String getHistoryofpresentillness() {
        return historyofpresentillness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.historyOfPresentIllness
     *
     * @param historyofpresentillness the value for userpatient.historyOfPresentIllness
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setHistoryofpresentillness(String historyofpresentillness) {
        this.historyofpresentillness = historyofpresentillness == null ? null : historyofpresentillness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userpatient.physicalExamResult
     *
     * @return the value of userpatient.physicalExamResult
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public String getPhysicalexamresult() {
        return physicalexamresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userpatient.physicalExamResult
     *
     * @param physicalexamresult the value for userpatient.physicalExamResult
     *
     * @mbg.generated Sun Dec 09 20:59:56 CST 2018
     */
    public void setPhysicalexamresult(String physicalexamresult) {
        this.physicalexamresult = physicalexamresult == null ? null : physicalexamresult.trim();
    }

	@Override
	public String toString() {
		return "UserPatientVM [id=" + id + ", price=" + price + ", status=" + status + ", symptom=" + symptom
				+ ", advice=" + advice + ", user=" + user + ", patient=" + patient + ", date=" + date + ", complained="
				+ complained + ", pastmedicalhistory=" + pastmedicalhistory + ", historyofpresentillness="
				+ historyofpresentillness + ", physicalexamresult=" + physicalexamresult + "]";
	}
    
}