package com.briup.Hospital.bean;

public class Drug {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.category_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.barcode
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.name
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.description
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.dosageform
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private String dosageform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.specifications
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private String specifications;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.unit
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.prime_cost
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Double primeCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.price
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.inventory
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer inventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug.minimum
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer minimum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.id
     *
     * @return the value of drug.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.id
     *
     * @param id the value for drug.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.category_id
     *
     * @return the value of drug.category_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.category_id
     *
     * @param categoryId the value for drug.category_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.barcode
     *
     * @return the value of drug.barcode
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.barcode
     *
     * @param barcode the value for drug.barcode
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.name
     *
     * @return the value of drug.name
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.name
     *
     * @param name the value for drug.name
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.description
     *
     * @return the value of drug.description
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.description
     *
     * @param description the value for drug.description
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.dosageform
     *
     * @return the value of drug.dosageform
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public String getDosageform() {
        return dosageform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.dosageform
     *
     * @param dosageform the value for drug.dosageform
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setDosageform(String dosageform) {
        this.dosageform = dosageform == null ? null : dosageform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.specifications
     *
     * @return the value of drug.specifications
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.specifications
     *
     * @param specifications the value for drug.specifications
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications == null ? null : specifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.unit
     *
     * @return the value of drug.unit
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.unit
     *
     * @param unit the value for drug.unit
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.prime_cost
     *
     * @return the value of drug.prime_cost
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Double getPrimeCost() {
        return primeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.prime_cost
     *
     * @param primeCost the value for drug.prime_cost
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setPrimeCost(Double primeCost) {
        this.primeCost = primeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.price
     *
     * @return the value of drug.price
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.price
     *
     * @param price the value for drug.price
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.inventory
     *
     * @return the value of drug.inventory
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.inventory
     *
     * @param inventory the value for drug.inventory
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug.minimum
     *
     * @return the value of drug.minimum
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getMinimum() {
        return minimum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug.minimum
     *
     * @param minimum the value for drug.minimum
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setMinimum(Integer minimum) {
        this.minimum = minimum;
    }
}