package com.briup.Hospital.bean;

public class PatientPhysicalexam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientphysicalexam.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientphysicalexam.cost
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientphysicalexam.patient_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientphysicalexam.physical_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer physicalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientphysicalexam.id
     *
     * @return the value of patientphysicalexam.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientphysicalexam.id
     *
     * @param id the value for patientphysicalexam.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientphysicalexam.cost
     *
     * @return the value of patientphysicalexam.cost
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientphysicalexam.cost
     *
     * @param cost the value for patientphysicalexam.cost
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientphysicalexam.patient_id
     *
     * @return the value of patientphysicalexam.patient_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientphysicalexam.patient_id
     *
     * @param patientId the value for patientphysicalexam.patient_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientphysicalexam.physical_id
     *
     * @return the value of patientphysicalexam.physical_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getPhysicalId() {
        return physicalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientphysicalexam.physical_id
     *
     * @param physicalId the value for patientphysicalexam.physical_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setPhysicalId(Integer physicalId) {
        this.physicalId = physicalId;
    }
}