package com.briup.Hospital.bean;

public class PatientDrug {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.cost
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.patient_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.drug_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer drugId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patientdrug.num
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientdrug.id
     *
     * @return the value of patientdrug.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientdrug.id
     *
     * @param id the value for patientdrug.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientdrug.cost
     *
     * @return the value of patientdrug.cost
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientdrug.cost
     *
     * @param cost the value for patientdrug.cost
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientdrug.patient_id
     *
     * @return the value of patientdrug.patient_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientdrug.patient_id
     *
     * @param patientId the value for patientdrug.patient_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientdrug.drug_id
     *
     * @return the value of patientdrug.drug_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getDrugId() {
        return drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientdrug.drug_id
     *
     * @param drugId the value for patientdrug.drug_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setDrugId(Integer drugId) {
        this.drugId = drugId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patientdrug.num
     *
     * @return the value of patientdrug.num
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patientdrug.num
     *
     * @param num the value for patientdrug.num
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}