package com.briup.Hospital.bean;

public class Physicalexam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physicalexam.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physicalexam.name
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physicalexam.price
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physicalexam.id
     *
     * @return the value of physicalexam.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physicalexam.id
     *
     * @param id the value for physicalexam.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physicalexam.name
     *
     * @return the value of physicalexam.name
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physicalexam.name
     *
     * @param name the value for physicalexam.name
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physicalexam.price
     *
     * @return the value of physicalexam.price
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physicalexam.price
     *
     * @param price the value for physicalexam.price
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}