package com.briup.Hospital.bean;

public class Privilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.name
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.url
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.role_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.id
     *
     * @return the value of privilege.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.id
     *
     * @param id the value for privilege.id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.name
     *
     * @return the value of privilege.name
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.name
     *
     * @param name the value for privilege.name
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.url
     *
     * @return the value of privilege.url
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.url
     *
     * @param url the value for privilege.url
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.role_id
     *
     * @return the value of privilege.role_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.role_id
     *
     * @param roleId the value for privilege.role_id
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}