package com.briup.Hospital.dao;

import com.briup.Hospital.bean.PatientDrug;
import com.briup.Hospital.bean.PatientDrugExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientDrugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    long countByExample(PatientDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    int deleteByExample(PatientDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    int insert(PatientDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    int insertSelective(PatientDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    List<PatientDrug> selectByExample(PatientDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    PatientDrug selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") PatientDrug record, @Param("example") PatientDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    int updateByExample(@Param("record") PatientDrug record, @Param("example") PatientDrugExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    int updateByPrimaryKeySelective(PatientDrug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patientdrug
     *
     * @mbg.generated Tue Apr 09 09:47:47 CST 2019
     */
    int updateByPrimaryKey(PatientDrug record);
}