package com.briup.Hospital.dao;

import com.briup.Hospital.bean.UserPatient;
import com.briup.Hospital.bean.UserPatientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserPatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    long countByExample(UserPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    int deleteByExample(UserPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    int insert(UserPatient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    int insertSelective(UserPatient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    List<UserPatient> selectByExample(UserPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    UserPatient selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPatient record, @Param("example") UserPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    int updateByExample(@Param("record") UserPatient record, @Param("example") UserPatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    int updateByPrimaryKeySelective(UserPatient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userpatient
     *
     * @mbg.generated Tue Apr 09 09:47:48 CST 2019
     */
    int updateByPrimaryKey(UserPatient record);
}